21:
	g++ -omain 21-demo.cpp
20:
	gcc -omain 20-qq-server.c
19:
	gcc -omain 19-qq-client.c -lcurses
18:
	gcc -omain 18-socket-server.c
17:
	gcc -omain 17-socket-client.c
16:
	gcc -omain 16-socket-server.c
15:
	gcc -omain 15-deamon.c
14:
	gcc -omain 14-fork.c
13:
	gcc -omain 13-execvp.c
12:
	gcc -omain 12-demo.c
10:
	gcc -oa 10-udp.c
	gcc -ob 11-udp.c
9:
	gcc -omain 9-demo.c
8:
	gcc -omain 8-signal.c
7:
	gcc -omain 7-demo.c
6:
	gcc -omain 6-demo.c
5:
	gcc -omain 5-fork.c
4:
	gcc -omain 4-popen.c
3:
	gcc -omain 3-test.c
2:
	gcc -omain 2-read-write.c
demo:
	gcc -omain 1-sbrk-brk.c

.PHONY:clean
clean:
	rm -rf *.o *.so *.a a.out \
		main maint tags cscope.* \
	   	my.sock a b



